# Generated by Django 2.1 on 2019-04-14 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customizations',
            field=models.TextField(null=True),
        ),
    ]
